baseURL = "https://www.nordbergmedia.se/"
disqusShortname = ""
enableEmoji = true
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Nordberg Media"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
URL = "kontakt"
name = "Kontakt"
weight = 1
[[menu.footer]]
URL = "verktyg"
name = "Verktyg"
weight = 2
[[menu.main]]
URL = "https://www.tjanster.nordbergmedia.se/"
name = "SEO Analys"
weight = 1
[[menu.main]]
URL = "kontakt"
name = "Kontakt"
weight = 1
[[menu.main]]
URL = "verktyg"
name = "verktyg"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Nordberg Media"
contact_form_action = "#"
copyright = "Nordberg Media &copy; 2020 Alla rättigheter reserverade | [Privacy Policy](/privacy-policy)"
description = "En SEO nörd som bloggar om nyheter, trender, guider & tips för alla som vill synas bättre på Google."
google_analitycs_id = ""
google_tag_manager = ""
home = "Hem"
logo = "images/logo.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "En SEO nörd som bloggar & hjälper lokala företagare få fler kunder."
[params.cta]
description = "**FÖRST TILL KVARN: 10st analyser finns kvar!** Täpp igen läckorna och få fler kunder med hjälp av en SEO-analys av er hemsida. Använd kampanjkoden: **NBM2020**."
enable = true
image = "images/hugo-muscot.png"
title = "<mark>Just Nu! 75% på SEO-analys ~~15000:-~~ 3750:-</mark>"
[params.cta.button]
enable = true
label = "mer info"
link = "https://www.tjanster.nordbergmedia.se/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-instagram"
link = "https://instagram.com/nordbergmedia"
[taxonomies]
category = "kategorier"
