[build]
  publish = "public"
  command = "hugo --gc --minify"
  
[build.environment]
  HUGO_VERSION = "0.65.3"
  HUGO_THEME = "northendlab-hugo"

[[redirects]]
  from = "/optimera-din-google-my-business-profil"
  to = "/optimera-google-my-business-2020"
  status = 301
  forced = true
